package com.pix.dayline.data

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class BetaReleaseNotesTest {
    @Test
    fun preservesAddedChangedFixedSections() {
        val raw = """
            # Dayline v0.17.4.beta

            ## Added
            - Added one thing.
            * Added another.

            ## Changed
            - Changed **important** behavior with `code`.

            ## Fixed
            - Fixed the updater.

            **Full Changelog**: https://github.com/0xpix/dayline/compare/old...new
        """.trimIndent()

        val cleaned = BetaReleaseNotes.clean(raw)

        assertTrue(cleaned.contains("## Added"))
        assertTrue(cleaned.contains("• Added one thing."))
        assertTrue(cleaned.contains("• Added another."))
        assertTrue(cleaned.contains("## Changed"))
        assertTrue(cleaned.contains("• Changed important behavior with code."))
        assertTrue(cleaned.contains("## Fixed"))
        assertTrue(cleaned.contains("• Fixed the updater."))
        assertFalse(cleaned.contains("Full Changelog"))
        assertFalse(cleaned.contains("https://"))
    }

    @Test
    fun ignoresUnsupportedHeadingsAndContentOutsideSupportedSections() {
        val raw = """
            Intro text that should disappear.

            ## Security
            - Internal note.

            ## Fixed
            - Visible fix.

            Footer text.
        """.trimIndent()

        val cleaned = BetaReleaseNotes.clean(raw)

        assertEquals(
            "## Fixed\n• Visible fix.\n• Footer text.",
            cleaned
        )
    }

    @Test
    fun unknownHeadingStopsThePreviousSection() {
        val raw = """
            ## Added
            - Visible addition.

            ## Security
            - Internal-only note.

            ## Fixed
            - Visible fix.
        """.trimIndent()

        val cleaned = BetaReleaseNotes.clean(raw)

        assertTrue(cleaned.contains("• Visible addition."))
        assertTrue(cleaned.contains("• Visible fix."))
        assertFalse(cleaned.contains("Internal-only note"))
    }

    @Test
    fun fallsBackForEmptyOrUnstructuredNotes() {
        val fallback = "## Changed\n• Bug fixes and Dayline polish."
        assertEquals(fallback, BetaReleaseNotes.clean(""))
        assertEquals(fallback, BetaReleaseNotes.clean("Plain autogenerated text only"))
    }


    @Test
    fun bundlesEveryMissedReleaseBetweenInstalledAndTargetVersions() {
        val bundled = BetaReleaseNotes.bundleBetween(
            currentVersion = "0.17.0.beta",
            targetVersion = "0.18.7.beta",
            releases = listOf(
                "0.18.7.beta" to "## Fixed\n- Latest fix.",
                "0.18.6.beta" to "## Added\n- New quick add guard.",
                "0.18.0.beta" to "## Changed\n- Room migration.",
                "0.17.4.beta" to "## Added\n- Reliability coverage.",
                "0.17.1.beta" to "## Fixed\n- First missed fix.",
                "0.17.0.beta" to "## Added\n- Already installed.",
                "0.16.1.beta" to "## Fixed\n- Older release."
            )
        )

        assertTrue(bundled.contains("# 0.18.7.beta"))
        assertTrue(bundled.contains("• Latest fix."))
        assertTrue(bundled.contains("# 0.18.6.beta"))
        assertTrue(bundled.contains("• New quick add guard."))
        assertTrue(bundled.contains("# 0.18.0.beta"))
        assertTrue(bundled.contains("# 0.17.4.beta"))
        assertTrue(bundled.contains("# 0.17.1.beta"))
        assertTrue(bundled.contains("• First missed fix."))
        assertFalse(bundled.contains("Already installed."))
        assertFalse(bundled.contains("Older release."))

        val versions = bundled.lineSequence().filter { it.startsWith("# ") }.toList()
        assertEquals(
            listOf(
                "# 0.18.7.beta",
                "# 0.18.6.beta",
                "# 0.18.0.beta",
                "# 0.17.4.beta",
                "# 0.17.1.beta"
            ),
            versions
        )
    }

    @Test
    fun capsVeryLongReleaseNotes() {
        val raw = buildString {
            appendLine("## Added")
            repeat(1_000) { appendLine("- This is a deliberately long release note entry number $it.") }
        }

        assertTrue(BetaReleaseNotes.clean(raw).length <= 3_000)
    }
}
