package com.pix.dayline.data

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class BetaReleaseNotesTest {
    @Test
    fun preservesAddedChangedFixedSections() {
        val raw = """
            # Dayline v0.17.4.beta

            ## Added
            - Added one thing.
            * Added another.

            ## Changed
            - Changed **important** behavior with `code`.

            ## Fixed
            - Fixed the updater.

            **Full Changelog**: https://github.com/0xpix/dayline/compare/old...new
        """.trimIndent()

        val cleaned = BetaReleaseNotes.clean(raw)

        assertTrue(cleaned.contains("## Added"))
        assertTrue(cleaned.contains("• Added one thing."))
        assertTrue(cleaned.contains("• Added another."))
        assertTrue(cleaned.contains("## Changed"))
        assertTrue(cleaned.contains("• Changed important behavior with code."))
        assertTrue(cleaned.contains("## Fixed"))
        assertTrue(cleaned.contains("• Fixed the updater."))
        assertFalse(cleaned.contains("Full Changelog"))
        assertFalse(cleaned.contains("https://"))
    }

    @Test
    fun ignoresUnsupportedHeadingsAndContentOutsideSupportedSections() {
        val raw = """
            Intro text that should disappear.

            ## Security
            - Internal note.

            ## Fixed
            - Visible fix.

            Footer text.
        """.trimIndent()

        val cleaned = BetaReleaseNotes.clean(raw)

        assertEquals(
            "## Fixed\n• Visible fix.\n• Footer text.",
            cleaned
        )
    }

    @Test
    fun unknownHeadingStopsThePreviousSection() {
        val raw = """
            ## Added
            - Visible addition.

            ## Security
            - Internal-only note.

            ## Fixed
            - Visible fix.
        """.trimIndent()

        val cleaned = BetaReleaseNotes.clean(raw)

        assertTrue(cleaned.contains("• Visible addition."))
        assertTrue(cleaned.contains("• Visible fix."))
        assertFalse(cleaned.contains("Internal-only note"))
    }

    @Test
    fun fallsBackForEmptyOrUnstructuredNotes() {
        val fallback = "## Changed\n• Bug fixes and Dayline polish."
        assertEquals(fallback, BetaReleaseNotes.clean(""))
        assertEquals(fallback, BetaReleaseNotes.clean("Plain autogenerated text only"))
    }

    @Test
    fun capsVeryLongReleaseNotes() {
        val raw = buildString {
            appendLine("## Added")
            repeat(1_000) { appendLine("- This is a deliberately long release note entry number $it.") }
        }

        assertTrue(BetaReleaseNotes.clean(raw).length <= 3_000)
    }
}
